{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ template "pod-labeller.name" . }}
    chart: {{ template "pod-labeller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
    - ""
    resources:
      - pods
      - service
    verbs:
      - get
      - list
      - watch
{{- end -}}