replicas: 1

global:
  name: pod-labeller
  namespace: kube-system

rbac:
  create: true
  pspEnabled: false

serviceAccount:
  create: true

image:
  repository: sandeeplamb/pod-labeller
  tag: release-0.0.1
  pullPolicy: Always
  namespace: kube-system
  backoffLimit: 3
  containerPort: 8080

extraEnv: {}
resources: {}
nodeSelector: {}
tolerations: 
affinity: {}
podAnnotations: {}