replicas: 1

global:
  name: pod-labeller
  namespace: scoreboards

rbac:
  create: true
  pspEnabled: false

serviceAccount:
  create: true

image:
  repository: sandeeplamb/pod-labeller
  tag: 1.0.0
  pullPolicy: Always
  namespace: scoreboards
  backoffLimit: 3
  containerPort: 8080

extraEnv: {}
resources: {}
nodeSelector: {}
tolerations: 
affinity: {}
podAnnotations: {}